Added a call to the SE capitalization lib to apply `kebabCase` to the…
ShipEngine/connect-cli pull request #122
Opened 2021-01-11 20:37 UTC by KaseyCantu

… defaults.name, this will remove any underscores in the current working directory name and change it into a hyphen separated version.

_Associated JIRA Ticket_
- [JIRA: DX-667](https://auctane.atlassian.net/browse/DX-667 "ShipEngine JIRA")

_To test these changes locally_:
- This command below will build a new binary, make a test directory, build a connect app in that directory, cat it's package.json, and remove the test directory afterward. (_`MacOS only`_ otherwise you will need to adjust it to work on `Windows`, or use `shx`)
- You can confirm that the `package.json.` name value is in `kebabCase` as opposed to the original current working directory name containing underscores. 

> **Info**: Be sure to run this in the root of this branch.
```bash
npm run build && mkdir test_connect_dir && ./bin/run init -y ./test_connect_dir && cat ./test_connect_dir/package.json && rm -rf ./test_connect_dir
```

2021-01-11 22:22 UTC, JamesMessinger requested changes

2021-01-11 22:22 UTC, JamesMessinger commented on src/core/generators/apps-new.ts
> +      name: capitalization.kebabCase(this.determineAppname().replace(/ /g, "-").replace("_", "-")),
I think both of the `.replace()` calls can be removed.  The first one is replaces spaces with hyphens, and the second one is replacing underscores with hyphens.  The `capitalization.kebabCase()` method already does both of those.

2021-01-11 23:41 UTC, KaseyCantu commented on src/core/generators/apps-new.ts
> +      name: capitalization.kebabCase(this.determineAppname().replace(/ /g, "-").replace("_", "-")),
Done! - I thought they might be redundant here once calling `capitalization.kebabCase()`, great catch James.

2021-01-11 23:57 UTC, silesky approved these changes
LGTM!

2021-01-12 02:25 UTC, JamesMessinger approved these changes
LGTM

2021-01-12 14:56 UTC, anthonyshull approved these changes

2021-01-19 21:03 UTC, merged