PLAT-1487 PLAT-1587 Updates to CLI
ShipEngine/connect-cli pull request #123
Opened 2021-01-12 19:44 UTC by justin-shipstation

- [PLAT-1487](https://auctane.atlassian.net/browse/PLAT-1487) - Remove getSalesOrdersByDate test from ShipEngine Connect
- [PLAT-1587](https://auctane.atlassian.net/browse/PLAT-1587) - `connect init` shouldn't create extra files for Order Apps

2021-01-12 20:12 UTC, jeversmann-shipstation commented on src/core/generators/apps-new.ts
> +    devDependencies.push("@shipengine/connect-sdk");
I think you'll need to update the template files to import from the correct library as well.

2021-01-12 20:30 UTC, justin-shipstation commented on src/core/generators/apps-new.ts
> +    devDependencies.push("@shipengine/connect-sdk");
Good Catch!

2021-01-12 20:32 UTC, justin-shipstation commented on src/core/generators/apps-new.ts
> +    devDependencies.push("@shipengine/connect-sdk");
@jeversmann-shipstation updated

2021-01-13 16:39 UTC, rkrauskopf requested changes
* Only use `@shipengine/connect` instead of `@shipengine/connect-sdk` in the generated order apps. See the [IBuy Sample app](https://github.com/ShipEngine/connect-samples/tree/main/iBuy) for reference.

* Why was the `getSalesOrdersByDate` integration test removed?

2021-01-13 17:20 UTC, justin-shipstation commented
> * Only use `@shipengine/connect` instead of `@shipengine/connect-sdk` in the generated order apps. See the [IBuy Sample app](https://github.com/ShipEngine/connect-samples/tree/main/iBuy) for reference.

So the decision is to change its dependency to the sdk because that is what is actually necessary for the project to run, the connect umbrella comes with a lot of baggage that is not necessary for runtime. We have mitigated this up until now with an aliasing hack but we would like to clean this up moving forward.

> * Why was the `getSalesOrdersByDate` integration test removed?

This was removed at the request of @jeversmann-shipstation

2021-01-13 17:59 UTC, jeversmann-shipstation commented
> Why was the getSalesOrdersByDate integration test removed?

Integration developers usually won't have the ability to make this test pass, and we don't want to prevent them from publishing or get them into the habit of skipping the tests every time.

2021-01-14 19:43 UTC, jeversmann-shipstation commented
We should remove this test too, since not every order app needs to implement acknowledge:
```
acknowledgeOrders
     FAIL  it validates the acknowledgeOrders method with notifications notifications: [object Object]
            Error: Error in the acknowledgeOrders method. NotImplementedError
                at Object.error (/Users/jeversmann/.nvm/versions/node/v12.14.0/lib/node_modules/@shipengine/connect/node_modules/@shipengine/connect-sdk/src/internal/common/errors.ts:42:17)
                at OrderApp.acknowledgeOrders (/Users/jeversmann/.nvm/versions/node/v12.14.0/lib/node_modules/@shipengine/connect/node_modules/@shipengine/connect-sdk/src/internal/orders/order-app.ts:153:13)
```

2021-03-12 17:56 UTC, ricky commented
development moved to https://github.com/ShipEngine/connect

2021-03-12 17:56 UTC, closed without merging